<?php
// Translation file for SubAlert. Supported languages: zh (Chinese), en (English)
return [
    'zh' => [
        // Navigation and common labels
        'dashboard'      => '仪表盘',
        'users'          => '用户管理',
        'settings'       => '系统设置',
        'stats'          => '数据统计',
        'templates'      => '模板管理',
        'tasks'          => '任务管理',
        'export_users'   => '导出用户',
        'logs'           => '操作日志',
        'backups'        => '备份管理',
        'logout'         => '退出登录',
        'login'          => '登录',
        'register'       => '注册',
        'profile'        => '个人资料',
        'subscriptions'  => '我的订阅',
        'reminders'      => '提醒管理',
        'stats_analysis' => '统计分析',
        'preferences'    => '偏好设置',
        'change_password'=> '修改密码',
        'forgot_password'=> '忘记密码',
        'back'           => '返回',
        'create_backup'  => '创建新备份',
        'no_backups'     => '当前没有备份文件。',
        'file_name'      => '文件名',
        'created_at'     => '创建时间',
        'size'           => '大小',
        'download'       => '下载',
        'export_subscriptions' => '导出订阅',
        'export_reminders' => '导出提醒',
    ],
    'en' => [
        'dashboard'      => 'Dashboard',
        'users'          => 'Users',
        'settings'       => 'System Settings',
        'stats'          => 'Statistics',
        'templates'      => 'Templates',
        'tasks'          => 'Tasks',
        'export_users'   => 'Export Users',
        'logs'           => 'Logs',
        'backups'        => 'Backups',
        'logout'         => 'Logout',
        'login'          => 'Login',
        'register'       => 'Register',
        'profile'        => 'Profile',
        'subscriptions'  => 'Subscriptions',
        'reminders'      => 'Reminders',
        'stats_analysis' => 'Stats Analysis',
        'preferences'    => 'Preferences',
        'change_password'=> 'Change Password',
        'forgot_password'=> 'Forgot Password',
        'back'           => 'Back',
        'create_backup'  => 'Create Backup',
        'no_backups'     => 'No backup files currently.',
        'file_name'      => 'File Name',
        'created_at'     => 'Created At',
        'size'           => 'Size',
        'download'       => 'Download',
        'export_subscriptions' => 'Export Subscriptions',
        'export_reminders' => 'Export Reminders',
    ],
];